# Generated by Django 5.2.6 on 2025-10-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
