# Generated by Django 5.2.6 on 2025-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_todolist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='delete_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='todolist',
            name='update_date',
            field=models.DateTimeField(default=None),
        ),
    ]
