# Generated by Django 5.2.6 on 2025-10-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_todolist_delete_date_todolist_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='update_date',
        ),
    ]
