# Generated by Django 5.2.6 on 2025-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0004_remove_todolist_delete_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='del_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
